.TH YOGRT 1 2015-06-25 "" "YOGRT"

.SH NAME
yogrt \- Command line interface to ligyogrt

.SH SYNOPSIS
.B yogrt
.I "[OPTIONS]"

.SH DESCRIPTION
.B yogrt
is a simple command line interface to the libyogrt library.

For more information on libyogrt see
.BR libyogrt (7).

.SH "OPTIONS"
.TP
.B -r
Output time remaining in seconds (default action).
.TP
.B -d
Increase debug verbosity, can be specified multiple times.
.TP
.B -h
Output help

.SH "SEE ALSO"
.BR libyogrt (7),
